---
title: "Análisis de datos en R"
subtitle: "Máster Universitario en Gestión Ambiental y Biodiversidad"
lightbox: auto
---

Esta es la web con los materiales del curso:

* **Clase 1:** Introducción a R. [Presentación](ADR-1_Intro.qmd){target="_blank"} - [Ejercicios](ADR-1-Ejercicios.qmd){target="_blank"} - [Homeworks](ADR-1-Homeworks.qmd){target="_blank"} - [Datos](data/Tema 1.zip){target="_blank"}

* **Clase 2:** Paquetes y graficado en R. [Presentación](ADR-2-Packages_plot.qmd){target="_blank"} - [Ejercicios](ADR-2-Ejercicios.qmd){target="_blank"} - [Homeworks](ADR-2-Homeworks.qmd){target="_blank"}

* **Clase 3:** Estadística descriptiva y contraste de hipótesis en R. [Presentación](ADR-3-Descriptive_hypothesis.qmd){target="_blank"} - [Ejercicios](ADR-3-Ejercicios.qmd){target="_blank"} - [Homeworks](ADR-3-Homeworks.qmd){target="_blank"} - [Datos](data/Tema 3.zip){target="_blank"}

* **Clase 4:** Introducción a Tidyverse. [Presentación](ADR-4-Tidyverse.qmd){target="_blank"}

Esta página web se construyó usando el sistema Quarto de RStudio. Para saber más sobre páginas web creadas con Quarto visita <https://quarto.org/docs/websites>.
